name: lidarmesure
description: "Transformez votre smartphone en un scanner 3D professionnel avec notre application LiDAR de pointe, qui offre des mesures de pied d'une précision inégalée grâce à une UI/UX moderne et dynamique pour une expérience utilisateur fluide et intuitive."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  printing: ^5.0.0
  pdf: ^3.0.0
  image_picker: '>=1.1.2'
  http: ^1.0.0
  supabase_flutter: '>=1.10.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  uuid: ^4.4.2
  flutter_animate: ^4.0.0
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/logo_solol.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/logo_solol.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/solol_B2B_platforme.png
  android: true
  ios: true
